# To run docker compose run this in terminal "docker-compose -f docker-compose.yml up -d"
# For 4 max sessions use "docker-compose -f docker-compose.yml up -d --scale chrome=4"
# To close all containers use "docker compose down"
version: "3"
services:
  #first chrome container config
  chrome1:
    build:
      context: .
      dockerfile: Dockerfile
    image: selenium/node-chrome:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    #go to "http://localhost:7900/?autoconnect=1&resize=scale&password=secret"
    #to see what is happening on this container
    ports:
      - "7900:7900"
      
  #second chrome container config
  chrome2:
    build:
      context: .
      dockerfile: Dockerfile
    image: selenium/node-chrome:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    #go to "http://localhost:7901/?autoconnect=1&resize=scale&password=secret"
    #to see what is happening on this container
    ports:
      - "7901:7900"

  selenium-hub:
    image: selenium/hub:4.16.1-20231212
    container_name: selenium-hub
    ports:
      - "4444:4444"